#+title: DOOM emacs literate configuration

* Config.el
** Frame size adjustment
#+begin_src emacs-lisp
;; start every frame maximized
;; (add-to-list 'default-frame-alist '(fullscreen . maximized))
(add-to-list 'default-frame-alist '(width . 160))
(add-to-list 'default-frame-alist '(height . 48))
#+end_src
** Fonts

*doom-font* The primary font to use
*doom-variable-pitch-font* A non-monospace font (where applicable)
*doom-big-font*  used for
*doom-big-font-mode*; use this for resentations or streaming.
*doom-symbol-font* -- for symbols
*doom-serif-font* -- for the `fixed-pitch-serif' face


If you or Emacs can't find your font, use 'M-x describe-font' to look them
up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
refresh your font settings. If Emacs still can't find your font, it likely
wasn't installed correctly. Font issues are rarely Doom issues!

#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Monaco" :size 15)
      doom-symbol-font (font-spec :family "Symbols Nerd Font")
     doom-variable-pitch-font (font-spec :family "DejaVu Sans Mono" :size 14))
#+end_src

** Theme

There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function. This is the default:

#+begin_src emacs-lisp
(setq doom-theme 'doom-one)
#+end_src

** Line Number

This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.

#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src

** Org File Directory
change `org-directory'. It must be set before org loads!
#+begin_src emacs-lisp
(setq org-directory "~/notes/")
#+end_src

** Org Heading and Title

#+begin_src emacs-lisp

;; Make the document title a bit bigger
(after! org
(set-face-attribute 'org-document-title nil :font "Monaco" :weight
'bold :height 1.8)

(dolist (face '((org-level-1 . 1.35)
                (org-level-2 . 1.3)
                (org-level-3 . 1.2)
                (org-level-4 . 1.1)
                (org-level-5 . 1.1)
                (org-level-6 . 1.1)
                (org-level-7 . 1.1)
                (org-level-8 . 1.1)))
  (when (facep (car face)) ; Check if the face is valid
    (set-face-attribute (car face) nil
                        :font "Monaco"
                        :weight 'bold
                        :height (cdr face))))



(require 'org-indent)
(set-face-attribute 'org-indent nil :inherit '(org-hide fixed-pitch))

(facep 'org-document-title)


;; (set-face-attribute 'org-block nil            :foreground nil :inherit
;; 'fixed-pitch :height 0.95)
;; (set-face-attribute 'org-code nil             :inherit '(shadow fixed-pitch) :height 0.95)
;; (set-face-attribute 'org-indent nil           :inherit '(org-hide fixed-pitch) :height 0.95)
;; (set-face-attribute 'org-verbatim nil         :inherit '(shadow fixed-pitch) :height 0.95)
;; (set-face-attribute 'org-special-keyword nil  :inherit '(font-lock-comment-face
;; fixed-pitch))
;; (set-face-attribute 'org-meta-line nil        :inherit '(font-lock-comment-face fixed-pitch))
;; (set-face-attribute 'org-checkbox nil         :inherit 'fixed-pitch)
  )
#+end_src
** Copy paste image from clipboard

#+begin_src emacs-lisp

(after! org-download
  (setq org-download-method 'directory)
  (setq org-download-image-dir (concat (file-name-sans-extension (buffer-file-name)) "-img"))
  ;; (setq org-download-image-org-width 600)
  (setq org-download-link-format "[[file:%s]]\n"
        org-download-abbreviate-filename-function #'file-relative-name)
  (setq org-download-link-format-function #'org-download-link-format-function-default))



#+end_src

* Packages.el

#+begin_src emacs-lisp :tangle packages.el
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

;; To install a package with Doom you must declare them here and run 'doom sync'
;; on the command line, then restart Emacs for the changes to take effect -- or


;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;; (package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/radian-software/straight.el#the-recipe-format
;; (package! another-package
;;   :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;; (package! this-package
;;   :recipe (:host github :repo "username/repo"
;;            :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;; (package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;; (package! builtin-package :recipe (:nonrecursive t))
;; (package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see radian-software/straight.el#279)
;; (package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;; (package! builtin-package :pin "1a2b3c4d5e")


;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;; (unpin! pinned-package)
;; ...or multiple packages
;; (unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;; (unpin! t)
#+end_src
