#! /bin/sh

sxhkd -c ~/.config/sxhkd/sxhkdrc ~/.config/sxhkd/sxhkdrc_bspwm &
nm-applet &
#picom &
polybar default&
#/usr/lib/xfce-polkit/xfce-polkit &
~/.config/bspwm/autostart &


bspc monitor -d I II III IV V #VI VII VIII IX X

bspc config border_width    0
bspc config window_gap      4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a XTerm state=floating follow=on
bspc rule -a jetbrains-studio state=floating follow=on
bspc rule -a Gvim state=tiled follow=on desktop='^2'
bspc rule -a Rhythmbox desktop='^6' follow=of
bspc rule -a discord state=tiled desktop='^3' follow=of
bspc rule -a Emacs state=tiled desktop='^3' follow=on
bspc rule -a Google-chrome state=tiled desktop='^1' follow=on
bspc rule -a Thunar state=tiled desktop='^4' follow=on
bspc rule -a xdman-Main:\* state=floating follow=of
bspc rule -a Wps state=tiled follow=on
bspc rule -a qBittorrent desktop='^5' state=tiled follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Nitrogen state=floating
bspc rule -a Screenkey manage=off
bspc rule -a jetbrains-idea state=floating
bspc rule -a persepolis state=floating
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Colorgrab state=floating
